version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: n8n_postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=n8nuser
      - POSTGRES_PASSWORD=MyDbPassword
      - POSTGRES_DB=n8n
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U n8nuser -d n8n"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:latest
    container_name: n8n_redis
    restart: always
    volumes:
      - redis_data:/data

  n8n:
    image: n8nio/n8n:1.113.1
    container_name: n8n_app
    restart: always
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8nuser
      - DB_POSTGRESDB_PASSWORD=MyDbPassword
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=MyAdminPassword
      - N8N_HOST=n8n.mycustomdevs.com
      - WEBHOOK_URL=https://n8n.mycustomdevs.com/
      - VUE_APP_URL_BASE_API=https://n8n.mycustomdevs.com/
      - GENERIC_TIMEZONE=America/Lima
      - N8N_EMAIL_FOOTER="Powered by MyCustomDevs"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  postgres_data:
  n8n_data: